stages:
  - Build
  - Linting
  - Test

Build:
  stage: Build
  script:
    - sudo apt-get update --quiet --yes
    - cat packages.txt | xargs sudo apt-get install --quiet --yes
    - pip3 install -r requirements.txt


Linting:
  stage: Linting
  script:
    - python3 -m pylint ./src || pylint-exit -cfail -efail $?

Test:
  stage: Test
  script:
    # Command to run the tests
  - python3 -m pytest --cov=src tests/
